### PR TITLE
Fix 0.5 deprecation warnings

### LINKED ISSUE #49: WARNING: New definition
Hi,

It seems like that GZip is not working on my version of Julia: v"0.5.0-dev+3438"

`julia> Pkg.test("GZip")
INFO: Testing GZip
WARNING: New definition 
    write(GZip.GZipStream, Array{#T<:Any, N<:Any}) at /home/julien/.julia/v0.5/GZip/src/GZip.jl:456
is ambiguous with: 
    write(Base.IO, Array{UInt8, N<:Any}) at io.jl:154.
To fix, define 
    write(GZip.GZipStream, Array{UInt8, N<:Any})
before the new definition.
WARNING: readall is deprecated, use readstring instead.
 [inlined code] from ./error.jl:26
 in depwarn(::ASCIIString, ::Symbol) at ./deprecated.jl:64
 [inlined code] from ./strings/io.jl:53
 in readall(::IOStream) at ./deprecated.jl:30
 in open(::Base.#readall, ::ASCIIString) at ./iostream.jl:114
 [inlined code] from /home/julien/.julia/v0.5/GZip/test/runtests.jl:32
 in anonymous at ./<no file>:4294967295
 in include(::ASCIIString) at ./boot.jl:234
 in include_from_node1(::UTF8String) at ./loading.jl:417
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /home/julien/.julia/v0.5/GZip/test/runtests.jl, in expression starting on line 27
Test Failed
  Expression: write(gzfile,data) == length(data.data)
   Evaluated: 440631 == 6449
ERROR: LoadError: There was an error during testing
 in record(::Base.Test.FallbackTestSet, ::Base.Test.Fail) at ./test.jl:322
 in do_test(::Base.Test.Returned, ::Expr) at ./test.jl:220
 [inlined code] from ./test.jl:137
 in anonymous at ./<no file>:4294967295
 in include(::ASCIIString) at ./boot.jl:234
 in include_from_node1(::UTF8String) at ./loading.jl:417
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /home/julien/.julia/v0.5/GZip/test/runtests.jl, in expression starting on line 27
================================[ ERROR: GZip ]=================================

failed process: Process(`/usr/bin/julia -Cx86-64 -J/usr/lib/x86_64-linux-gnu/julia/sys.so --compile=yes --check-bounds=yes --code-coverage=none --color=yes /home/julien/.julia/v0.5/GZip/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: Base.Pkg.PkgError("GZip had test errors")
 [inlined code] from ./strings/io.jl:33
 in #test#55(::Bool, ::Any, ::Array{AbstractString,1}) at ./pkg/entry.jl:671
 [inlined code] from ./int.jl:32
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::ASCIIString) at ./file.jl:48
 in #cd#1(::Array{Any,1}, ::Any, ::Any, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1}}) at ./pkg/dir.jl:31
 [inlined code] from ./boot.jl:304
 in #test#3(::Bool, ::Any, ::ASCIIString, ::Vararg{ASCIIString}) at ./pkg.jl:228
 in eval(::Module, ::Any) at ./boot.jl:237
`

'28 required packages:
 - ApproxFun                     0.1.0
 - BlackBoxOptim                 0.2.0
 - Bokeh                         0.2.0
 - Cbc                           0.2.0
 - DataFrames                    0.7.0
 - Debug                         0.1.6
 - Distributions                 0.8.10
 - FactCheck                     0.4.2
 - FastGaussQuadrature           0.0.3
 - ForwardDiff                   0.1.6
 - GLM                           0.5.1
 - Gadfly                        0.4.2
 - HDF5                          0.5.8
 - IJulia                        1.1.9
 - Ipopt                         0.2.1
 - JLD                           0.5.9
 - JuMP                          0.12.2
 - LaTeXStrings                  0.1.6
 - Lumberjack                    2.0.1
 - NLopt                         0.3.1
 - Optim                         0.4.4
 - PyCall                        1.4.0
 - PyPlot                        2.1.1
 - QuantEcon                     0.4.2
 - Roots                         0.1.26
 - Sobol                         0.1.2
 - StochasticSearch              0.2.2
 - Winston                       0.11.13
65 additional packages:
 - ApproXD                       0.0.0-             master (unregistered)
 - ArrayViews                    0.6.4
 - AutoHashEquals                0.0.9
 - BinDeps                       0.3.21
 - Blosc                         0.1.4
 - Cairo                         0.2.31
 - Calculus                      0.1.14
 - Clustering                    0.5.0
 - Codecs                        0.1.5
 - ColorTypes                    0.2.2
 - Colors                        0.6.3
 - Combinatorics                 0.3.2
 - CompEcon                      0.0.0-             master (unregistered)
 - Compat                        0.7.14
 - Compose                       0.4.2
 - Conda                         0.1.9
 - Contour                       0.1.0
 - Copulas                       0.0.0-             master (unregistered)
 - DSP                           0.0.11
 - DataArrays                    0.2.20
 - DataStructures                0.4.3
 - Dates                         0.4.4
 - Distances                     0.3.0
 - Docile                        0.5.23
 - DualNumbers                   0.2.2
 - FileIO                        0.0.4
 - FixedPointNumbers             0.1.3
 - FixedSizeArrays               0.1.0
 - GZip                          0.2.18
 - Graphics                      0.1.3
 - Grid                          0.4.0
 - Hexagons                      0.0.4
 - IniFile                       0.2.5
 - Iterators                     0.1.9
 - JSON                          0.5.0
 - KernelDensity                 0.1.2
 - Lazy                          0.10.1
 - LightGraphs                   0.5.2
 - LightXML                      0.2.1
 - Loess                         0.0.6
 - MOpt                          0.0.0-             master (unregistered)
 - MacroTools                    0.3.0
 - MathProgBase                  0.4.3
 - Measures                      0.0.2
 - Mustache                      0.0.14
 - NaNMath                       0.2.1
 - Nettle                        0.2.3
 - PDMats                        0.4.1
 - ParserCombinator              1.7.8
 - Plots                         0.5.4
 - Polynomials                   0.0.5
 - Reexport                      0.0.3
 - Requires                      0.2.2
 - ReverseDiffSparse             0.5.5
 - SHA                           0.1.2
 - Showoff                       0.0.6
 - Smolyak                       0.0.0-             master (unregistered)
 - SortingAlgorithms             0.0.6
 - StackTraces                   0.1.1
 - StatsBase                     0.8.0
 - StatsFuns                     0.2.0
 - Tk                            0.3.7
 - URIParser                     0.1.3
 - WoodburyMatrices              0.1.5
 - ZMQ                           0.3.1
'

Any reason why?
Any help would be strongly appreciated.

Cheers,
Julien

### PR DESCRIPTION
**Pull request by Keno**
Also fixes #49, #47.

### CODE REVIEW

File: test/runtests.jl [hunk 1]
```diff
@@ -1,4 +1,5 @@
 using Compat
+using Compat: readstring
```
Comment (yuyichao) [inline test/runtests.jl]: I don't think this is needed?

Comment (Keno) [inline test/runtests.jl]: Can't hurt.

**Comment by kmsquire** [comment]
Since it's only v0.3 that is failing, and previous versions of `GZip.jl` should generally work on v0.3, I would suggest just dropping support.
